prompt Loading ju_podaci_osobe...
MERGE INTO JURIST.JU_PODACI_OSOBE A USING
 (SELECT
  1 as ID,
  1 as JUS_ID,
  1 as TOA_ID,
  'V' as VJEROVNIK_ILI_DUZNIK,
  'ZAJEDNIÈKI ODVJETNIÈKI URED JOSIP JANKOVIÆ,I MATE BURAZIN, DARIO BANIÆ I TOMISLAV HORAÈKI' as NAZIV,
  16977149814 as OIB,
  'Vranicanijeva 5/I' as ULICA_I_BROJ,
  '	47000 Karlovac' as GRAD
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, JUS_ID, TOA_ID, VJEROVNIK_ILI_DUZNIK, NAZIV, 
  OIB, ULICA_I_BROJ, GRAD)
VALUES (
  B.ID, B.JUS_ID, B.TOA_ID, B.VJEROVNIK_ILI_DUZNIK, B.NAZIV, 
  B.OIB, B.ULICA_I_BROJ, B.GRAD)
WHEN MATCHED THEN
UPDATE SET 
  A.JUS_ID = B.JUS_ID,
  A.TOA_ID = B.TOA_ID,
  A.VJEROVNIK_ILI_DUZNIK = B.VJEROVNIK_ILI_DUZNIK,
  A.NAZIV = B.NAZIV,
  A.OIB = B.OIB,
  A.ULICA_I_BROJ = B.ULICA_I_BROJ,
  A.GRAD = B.GRAD
/
commit
/
